// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsKWcpiCg1Z-B2lti5Lgbt3YizitPPr40',
    appId: '1:479932286603:web:043b5c3518ffb04995368e',
    messagingSenderId: '479932286603',
    projectId: 'smartwallet-3c9c4',
    authDomain: 'smartwallet-3c9c4.firebaseapp.com',
    storageBucket: 'smartwallet-3c9c4.appspot.com',
    measurementId: 'G-5EYKEWLQPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGgakd_MkhNIABQhBl8CvmynTkGwSYJN4',
    appId: '1:479932286603:android:283496838087901795368e',
    messagingSenderId: '479932286603',
    projectId: 'smartwallet-3c9c4',
    storageBucket: 'smartwallet-3c9c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTI-PZ1R__VK-oc8B3eljBgyYgfjSwXZE',
    appId: '1:479932286603:ios:4eb3f4f0ba555c0a95368e',
    messagingSenderId: '479932286603',
    projectId: 'smartwallet-3c9c4',
    storageBucket: 'smartwallet-3c9c4.appspot.com',
    iosBundleId: 'com.example.smartWallet',
  );
}
